[package]
name = "smelt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = "0.7.0"
mlua = { version = "0.9.7", features = ["lua54", "vendored"] }
sha256 = "1.5.0"
